project:
  type: default
  output-dir: _output

format:
  typst:
    papersize: us-letter
    margin:
      x: 1.25in
      y: 1.25in
  html:
    theme: cosmo
    toc: true
    embed-resources: true

execute:
  echo: false
  warning: false
